/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.popup.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param popupId 
 * @param clientId 
 * @param sourceId 
 */

data class ConfirmRequest (

    @Json(name = "popup_id")
    var popupId: kotlin.Int? = null,

    @Json(name = "client_id")
    var clientId: kotlin.String? = null,

    @Json(name = "source_id")
    var sourceId: kotlin.Int? = null

)

