/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.popup.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param code 
 * @param type 
 * @param message 
 */

data class ModelApiResponse (

    @Json(name = "code")
    var code: kotlin.Int? = null,

    @Json(name = "type")
    var type: kotlin.String? = null,

    @Json(name = "message")
    var message: kotlin.String? = null

)

