/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.popup.sdk.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param popupId 
 * @param navlink 
 * @param action 
 * @param content 
 * @param style 
 */

data class Popup (

    @Json(name = "popup_id")
    var popupId: kotlin.Long,

    @Json(name = "navlink")
    var navlink: kotlin.String,

    @Json(name = "action")
    var action: kotlin.String? = null,

    @Json(name = "content")
    var content: PopupContent? = null,

    @Json(name = "style")
    var style: PopupStyle? = null

)

