/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.popup.sdk.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param mainColor 
 * @param secondColor 
 */

data class PopupResponseStyle (

    @Json(name = "main_color")
    val mainColor: kotlin.String? = null,

    @Json(name = "second_color")
    val secondColor: kotlin.String? = null

)

