/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.popup.sdk.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param title 
 * @param subtitle 
 * @param imageUrl 
 * @param text 
 * @param button 
 * @param promocode 
 */

data class PopupResponseContent (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "subtitle")
    val subtitle: kotlin.String? = null,

    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "button")
    val button: PopupResponseContentButton? = null,

    @Json(name = "promocode")
    val promocode: kotlin.String? = null

)

