/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.popup.sdk.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param title 
 * @param subtitle 
 * @param imageUrl 
 * @param text 
 * @param button 
 */

data class PopupContent (

    @Json(name = "title")
    var title: kotlin.String? = null,

    @Json(name = "subtitle")
    var subtitle: kotlin.String? = null,

    @Json(name = "image_url")
    var imageUrl: kotlin.String? = null,

    @Json(name = "text")
    var text: kotlin.String? = null,

    @Json(name = "button")
    var button: PopupContentButton? = null

)

